# Generated by Django 4.1.1 on 2022-09-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('UUID', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30)),
                ('company_ceo', models.CharField(max_length=40)),
                ('company_address', models.CharField(max_length=50)),
                ('inception_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('UUID', models.AutoField(primary_key=True, serialize=False)),
                ('team_leader', models.CharField(max_length=40)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
