# Generated by Django 4.1.1 on 2022-09-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='UUID',
            new_name='UUID_company',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='UUID',
            new_name='UUID_team',
        ),
    ]
